name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false # short-circuit if vuln is found
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --fail-on=all

      # Archive code into a ZIP file (only runs if no vulnerabilities are found)
      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: . # Root directory to archive
          file_path: code.zip # Path for the resulting ZIP file
